#!/bin/bash

# Menghapus folder .acme.sh
rm -rf ~/.acme.sh

# Mematikan layanan Docker Marzban tanpa tampilan log
echo "Mematikan layanan Docker Marzban..."
cd /opt/marzban && docker compose down > /dev/null 2>&1

# Kembali ke home directory
cd

# Konfigurasi domain
DOMAIN1=$(cat /etc/data/domain1)
DOMAIN2=$(cat /etc/data/domain2)
EMAIL=$(cat /etc/data/email)

# Menginstal acme.sh
echo "Menginstal acme.sh..."
curl -s https://get.acme.sh | sh -s email=$EMAIL > /dev/null 2>&1

# Atur Let's Encrypt sebagai server CA default tanpa progress
~/.acme.sh/acme.sh --set-default-ca --server letsencrypt --quiet

# Mendaftarkan akun dan menerbitkan sertifikat untuk domain pertama
echo "Menerbitkan sertifikat untuk domain pertama ($DOMAIN1)..."
/root/.acme.sh/acme.sh --register-account -m "$EMAIL" --quiet
/root/.acme.sh/acme.sh --issue -d "$DOMAIN1" --standalone -k ec-256 --quiet

# Memasang sertifikat untuk domain pertama tanpa progress
echo "Memasang sertifikat untuk domain pertama ($DOMAIN1)..."
~/.acme.sh/acme.sh --installcert -d "$DOMAIN1" \
  --fullchainpath /var/lib/marzban/certs/domain1/xray.crt \
  --keypath /var/lib/marzban/certs/domain1/xray.key --ecc --quiet

# Mendaftarkan akun dan menerbitkan sertifikat untuk domain kedua
echo "Menerbitkan sertifikat untuk domain kedua ($DOMAIN2)..."
/root/.acme.sh/acme.sh --issue -d "$DOMAIN2" --standalone -k ec-256 --quiet

# Memasang sertifikat untuk domain kedua tanpa progress
echo "Memasang sertifikat untuk domain kedua ($DOMAIN2)..."
~/.acme.sh/acme.sh --installcert -d "$DOMAIN2" \
  --fullchainpath /var/lib/marzban/certs/domain2/xray.crt \
  --keypath /var/lib/marzban/certs/domain2/xray.key --ecc --quiet

# Menghidupkan kembali layanan Docker Marzban tanpa tampilan log
echo "Menghidupkan kembali layanan Docker Marzban..."
cd /opt/marzban && docker compose up -d > /dev/null 2>&1

# Kembali ke home directory
cd

echo "Proses pembaruan sertifikat selesai."
